name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: g++ Lab1.cpp -o Lab1
        command: "./Lab1"
        input: '212.75'
        expected-output: 212.75 degrees Fahrenheit is equal to 100.42 degrees Celsius!
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: g++ Lab1.cpp -o Lab1
        command: "./Lab1"
        input: '37.25'
        expected-output: 37.25 degrees Fahrenheit is equal to 2.92 degrees Celsius!
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: g++ Lab1.cpp -o Lab1
        command: "./Lab1"
        input: '17'
        expected-output: 17 degrees Fahrenheit is equal to -8.33 degrees Celsius!
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
      with:
        runners: test-1,test-2,test-3
